<?php
/**
 * Builder: Implementation_Guide.md
 *
 * Port of base44/functions/generateFiles/entry.ts lines 549-670.
 * v2.0 three-discipline guide (SEO + AEO + GEO) with platform-specific
 * SEO steps. Basic-tier file; Complete tier content gated inline.
 */

declare(strict_types=1);

/**
 * @param array<string, mixed> $ctx
 * @return array{'Implementation_Guide.md': string}
 */
function build_implementation_guide_md(array $ctx): array
{
    $tier       = $ctx['package_tier'];
    $data       = $ctx['data'];
    $ex         = $ctx['ex'];
    $today      = $ctx['today'];
    $url        = $ctx['website_url'];
    $businessName = $ctx['businessNameFinal'];
    $email      = (string) ($data['contactEmail'] ?? 'support');

    $platformName = (string) ($data['platform'] ?? $ex['platform'] ?? 'Custom/Other');

    $platformSeoSteps = [
        'WordPress' => [
            '1. Install RankMath (free) or Yoast SEO Premium. Both support custom JSON-LD.',
            '2. Paste each schema-*.json file into RankMath → Titles & Meta → Global Meta → Advanced → Custom JSON-LD (or the Yoast equivalent).',
            "3. Upload robots.txt, sitemap.xml, ai-sitemap.xml, llm.txt, humans.txt, security.txt, and meta-tags.html content to /public_html/ via your host's file manager or SFTP.",
            "4. In your theme's functions.php (or a snippets plugin), add the meta-tags.html content inside wp_head via an add_action hook if your SEO plugin doesn't already cover Open Graph.",
        ],
        'Shopify' => [
            '1. In Shopify admin: Online Store → Preferences → Edit robots.txt.liquid. Merge the provided robots.txt directives.',
            "2. Online Store → Navigation → Pages. Create a page for llm.txt, llms.txt, and llms-full.txt if Shopify won't serve them at the root (Shopify restricts root-level static files). Alternatively, use a subdomain or reverse proxy.",
            '3. Paste schema JSON-LD blocks into theme.liquid within <head>, wrapped in <script type="application/ld+json"> tags. Do this before </head>.',
            '4. meta-tags.html content goes into theme.liquid <head> as well.',
        ],
        'Wix' => [
            '1. Settings → Custom Code. Add each schema-*.json as a Custom Code snippet targeting <head> on all pages, wrapped in <script type="application/ld+json">.',
            '2. meta-tags.html content: paste as another Custom Code snippet targeting <head>.',
            '3. Upload robots.txt directives via Marketing & SEO → SEO Settings → Advanced SEO → robots.txt.',
            "4. Submit sitemap.xml via Google Search Console — Wix generates its own sitemap at /sitemap.xml, so you'll use the Wix-managed file unless you're on Premium with DNS control.",
        ],
        'Squarespace' => [
            '1. Settings → Advanced → Code Injection → Header. Paste each schema-*.json wrapped in <script type="application/ld+json"> tags, followed by the meta-tags.html content.',
            "2. Squarespace automatically serves robots.txt at /robots.txt — you can't replace it, but you can review it at /robots.txt.",
            '3. sitemap.xml is auto-generated by Squarespace. Use the provided sitemap.xml as a reference if customizing via Developer Mode.',
            '4. llm.txt, llms.txt, and similar files require Developer Mode or a subdomain.',
        ],
        'Webflow' => [
            '1. Project Settings → Custom Code → Head Code. Paste each schema-*.json inside <script type="application/ld+json"> tags.',
            '2. Paste meta-tags.html content into Head Code as well.',
            '3. Project Settings → SEO → Indexing → robots.txt: paste the provided content.',
            '4. Webflow auto-generates a sitemap.xml. Use the provided sitemap.xml as a reference for structure.',
        ],
        'Framer' => [
            '1. Site Settings → General → Custom Code → End of <head>. Paste meta-tags.html and each schema-*.json (wrapped in <script type="application/ld+json">).',
            "2. Site Settings → SEO → Custom Domain: upload robots.txt at the domain level if supported, or rely on Framer's defaults.",
            '3. Framer generates sitemap.xml automatically.',
        ],
        'Kajabi' => [
            '1. Site Settings → Advanced Settings → Site header code. Paste schema JSON-LD blocks and meta-tags.html content.',
            '2. Kajabi manages robots.txt at the account level; request custom edits from support if needed.',
            '3. llm.txt and similar static files need a subdomain or external host.',
        ],
        'Ghost' => [
            '1. Admin → Settings → Code Injection → Site Header. Paste schema JSON-LD and meta-tags.html.',
            '2. Admin → Settings → Labs or via theme: edit robots.txt.',
            '3. Ghost auto-generates sitemap.xml.',
        ],
        'Custom/Other' => [
            '1. Upload robots.txt, sitemap.xml, ai-sitemap.xml, llm.txt, humans.txt, security.txt, and meta-tags.html (as HTML) to your site root directory.',
            '2. In your HTML <head>, paste each schema-*.json wrapped in <script type="application/ld+json"> tags.',
            '3. Also in <head>, paste the meta-tags.html content.',
            '4. If you use a CDN, purge cache after upload.',
        ],
    ];
    $seoStepLines = implode("\n", $platformSeoSteps[$platformName] ?? $platformSeoSteps['Custom/Other']);

    $aeoExtra = $tier === 'complete'
        ? "- **llms.txt** and **llms-full.txt** also go at the site root: {$url}/llms.txt, {$url}/llms-full.txt.\n- **.well-known/ai.json** goes at {$url}/.well-known/ai.json."
        : '';

    $geoBlock = $tier === 'complete'
        ? "- Open `geo-content-brief.md`. Use the **Brand Positioning Statement** as canonical copy in your About page, hero section, and PR boilerplate.\n"
          . "- Publish the **Quotable Expert Answers** as a FAQ page on your site. AI systems preferentially cite FAQ-formatted content.\n"
          . "- Work through `topical-authority-plan.md` month by month. Don't skip the internal linking map.\n"
          . "- Reference `entity-map.json` when writing author bios, press kits, or bio pages — it's the canonical list of entities, claims, and relationships AI should associate with your brand.\n"
          . "- Submit `geo-qa-snippets.json` structure to any AI-friendly directories or datasets your niche has."
        : '- Complete tier unlocks the GEO content brief, entity map, Q&A snippets, topical authority plan, and article schema template. Upgrade if you want structured GEO deliverables.';

    $lines = [
        "# Implementation Guide — {$businessName}",
        '',
        "Detected platform: **{$platformName}**  ",
        "Package tier: **" . strtoupper($tier) . "**  ",
        "Generated: {$today}",
        '',
        'This guide covers three disciplines: **SEO** (traditional search), **AEO** (AI answer engines), and **GEO** (AI-generated search results). Complete the quick start first; tackle the rest in order.',
        '',
        '---',
        '',
        '## Quick Start (5 minutes)',
        '',
        "1. Upload `robots.txt`, `sitemap.xml`, and `llm.txt` to your site root so they resolve at {$url}/robots.txt etc.",
        "2. Paste the contents of `meta-tags.html` into every page's <head> (or global head, depending on platform).",
        '3. Paste each `schema-*.json` into a <script type="application/ld+json"> block in <head>.',
        '4. Submit `sitemap.xml` in Google Search Console.',
        '5. Read `seo-audit.md` for your personalized quick-win list.',
        '',
        '---',
        '',
        '## 1. SEO Implementation',
        '',
        "### Platform-specific steps for {$platformName}",
        '',
        $seoStepLines,
        '',
        '### Validate',
        '',
        '- Run every schema file through https://validator.schema.org and https://search.google.com/test/rich-results.',
        "- Use Google Search Console's URL Inspection tool to confirm canonical, indexing, and rich results status.",
        '',
        '## 2. AEO Implementation',
        '',
        "- **llm.txt** goes at the site root: {$url}/llm.txt. Some crawlers also check /.well-known/llm.txt — symlink or mirror if your host allows it.",
        $aeoExtra,
        '- Verify each file loads by visiting the URL in a private/incognito window. All must return HTTP 200.',
        '- In robots.txt, confirm the AI crawler directives match your stated preferences.',
        '',
        '## 3. GEO Implementation',
        '',
        $geoBlock,
        '',
        '## 4. Verification',
        '',
        '- Every schema JSON → Google Rich Results Test + schema.org validator.',
        '- `sitemap.xml` → Google Search Console submission.',
        '- `seo-audit.md` → work through the Quick Wins list in order.',
        '- Confirm OpenGraph tags render correctly using https://www.opengraph.xyz.',
        '',
        '## 5. Maintenance Schedule',
        '',
        '- **Quarterly:** re-run the generator so llm.txt, schema, and the GEO brief reflect your current offering, credibility signals, and proof points.',
        '- **On launch of any new product, program, or major hire:** re-run immediately.',
        '- **Annually:** review and reaffirm topic ownership (Q11) — topical authority compounds over time only if the topic set stays stable.',
        '',
        '## Support',
        '',
        "Questions? Contact: {$email}",
        '',
    ];

    return ['Implementation_Guide.md' => implode("\n", $lines)];
}
