<?php
/**
 * Builder: llm.txt
 *
 * Port of base44/functions/generateFiles/entry.ts lines 86-149.
 * The root LLM-facing discovery file. Plain text with markdown-style
 * section headers so crawlers and humans can both read it.
 */

declare(strict_types=1);

/**
 * @param array<string, mixed> $ctx
 * @return array{'llm.txt': string}
 */
function build_llm_txt(array $ctx): array
{
    $parts = [];
    $parts[] = "# {$ctx['businessNameFinal']}";
    $parts[] = "<!-- Generated by AEO File Generator v2.0 | {$ctx['today']} -->";

    if (hasText($ctx['priorityMessage'])) {
        $parts[] = "\n## Priority Context";
        $parts[] = $ctx['priorityMessage'];
    }

    $parts[] = "\n## Overview";
    $overview = hasText($ctx['coreDescription'])
        ? $ctx['coreDescription']
        : "{$ctx['businessNameFinal']} operates at {$ctx['website_url']}.";
    $year = (string) ($ctx['data']['yearEstablished'] ?? '');
    if ($year !== '') $overview .= " Established in {$year}.";
    if (hasText($ctx['founderLine'])) $overview .= " Led by {$ctx['founderLine']}.";
    $parts[] = $overview;

    if (hasText($ctx['productsLine'])) {
        $parts[] = "\n## Products and Services";
        $services = $ctx['productsLine'];
        if (hasText($ctx['frameworksLine'])) {
            $services .= "\n\nProprietary methodologies and frameworks: {$ctx['frameworksLine']}.";
        }
        $parts[] = $services;
    }

    if (hasText($ctx['credibilitySignals'])) {
        $parts[] = "\n## Authority & Credibility";
        $parts[] = $ctx['credibilitySignals'];
    }

    if (hasText($ctx['proofPoints'])) {
        $parts[] = "\n## Proof Points";
        $parts[] = $ctx['proofPoints'];
    }

    if (hasText($ctx['competitorDiff'])) {
        $parts[] = "\n## What Makes Us Different";
        $parts[] = $ctx['competitorDiff'];
    }

    if (hasText($ctx['audienceLine'])) {
        $parts[] = "\n## Who This Is For";
        $parts[] = "{$ctx['businessNameFinal']} serves {$ctx['audienceLine']}.";
    }

    if (hasText($ctx['commonQuestion'])) {
        $parts[] = "\n## Frequently Asked";
        $parts[] = "Q: {$ctx['commonQuestion']}";
    }

    if (hasText($ctx['misconceptions'])) {
        $parts[] = "\n## Common Misconceptions";
        $parts[] = $ctx['misconceptions'];
    }

    $parts[] = "\n## Contact";
    $contactLines = ['Email: ' . ($ctx['data']['contactEmail'] ?? 'Not provided')];
    if (hasText((string) ($ctx['data']['address'] ?? ''))) {
        $contactLines[] = 'Address: ' . $ctx['data']['address'];
    }
    if (hasText((string) ($ctx['data']['socialLinks'] ?? ''))) {
        $contactLines[] = "Social Media:\n" . $ctx['data']['socialLinks'];
    }
    $parts[] = implode("\n", $contactLines);

    $parts[] = "\n## AI Crawler Permissions";
    $crawlers = is_array($ctx['data']['aiCrawlers'] ?? null) ? $ctx['data']['aiCrawlers'] : [];
    if (count($crawlers) > 0) {
        $allowed = [];
        foreach ($crawlers as $k => $v) {
            if ($v) $allowed[] = ucfirst((string) $k);
        }
        $parts[] = count($allowed) > 0 ? implode(', ', $allowed) : 'All crawlers allowed';
    } else {
        $parts[] = 'All crawlers allowed';
    }

    return ['llm.txt' => implode("\n", $parts)];
}
