<?php
/**
 * Builder: meta-tags.html
 *
 * Port of base44/functions/generateFiles/entry.ts lines 415-420.
 * Copy-paste Open Graph + Twitter Card block for the user's site head.
 */

declare(strict_types=1);

/**
 * @param array<string, mixed> $ctx
 * @return array{'meta-tags.html': string}
 */
function build_meta_tags_html(array $ctx): array
{
    $descRaw = $ctx['coreDescription'] !== '' ? $ctx['coreDescription'] : $ctx['productsLine'];
    $metaDesc = mb_substr(
        str_replace('"', '&quot;', explode("\n", (string) $descRaw)[0] ?? ''),
        0,
        200
    );
    $metaTitle = str_replace('"', '&quot;', $ctx['businessNameFinal']);
    $metaImage = (string) ($ctx['ex']['logoUrl'] ?? '');

    $imageLine = $metaImage !== ''
        ? "<meta property=\"og:image\" content=\"{$metaImage}\" />\n"
        : "<!-- <meta property=\"og:image\" content=\"https://your-site.com/path/to/image.png\" /> -->\n";
    $twitterImageLine = $metaImage !== ''
        ? "<meta name=\"twitter:image\" content=\"{$metaImage}\" />\n"
        : "<!-- <meta name=\"twitter:image\" content=\"https://your-site.com/path/to/image.png\" /> -->\n";

    $html = "<!-- ============================================\n"
          . "     OPEN GRAPH & TWITTER CARD META TAGS\n"
          . "     Copy and paste this block into your <head> tag\n"
          . "     Generated by AEO File Generator v2.0 — {$ctx['today']}\n"
          . "     ============================================ -->\n"
          . "<meta property=\"og:title\" content=\"{$metaTitle}\" />\n"
          . "<meta property=\"og:description\" content=\"{$metaDesc}\" />\n"
          . "<meta property=\"og:type\" content=\"website\" />\n"
          . "<meta property=\"og:url\" content=\"{$ctx['website_url']}\" />\n"
          . $imageLine
          . "<meta name=\"twitter:card\" content=\"summary_large_image\" />\n"
          . "<meta name=\"twitter:title\" content=\"{$metaTitle}\" />\n"
          . "<meta name=\"twitter:description\" content=\"{$metaDesc}\" />\n"
          . $twitterImageLine;

    return ['meta-tags.html' => $html];
}
