import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';
import JSZip from 'npm:jszip';

Deno.serve(async (req) => {
  let generation_id;
  
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json();
    generation_id = body.generation_id;

    if (!generation_id) {
      return Response.json({ error: 'Missing generation_id' }, { status: 400 });
    }

    let generation = await base44.asServiceRole.entities.Generation.get(generation_id);

    if (!generation || generation.user_id !== user.id) {
      return Response.json({ error: 'Generation not found or unauthorized' }, { status: 404 });
    }

    if (generation.status === 'generating') {
      return Response.json({ error: 'Generation already in progress' }, { status: 409 });
    }

    // Set status to generating
    await base44.asServiceRole.entities.Generation.update(generation_id, { status: 'generating' });
    generation = await base44.asServiceRole.entities.Generation.get(generation_id);

    const { website_url, business_name, package_tier, questionnaire_data } = generation;
    const data = questionnaire_data || {};

    // Pull enriched data from the analysis record if available
    let analysisExtracted = {};
    if (generation.analysis_id) {
      try {
        const analysis = await base44.asServiceRole.entities.Analysis.get(generation.analysis_id);
        analysisExtracted = analysis?.extracted_data || {};
      } catch (_) {}
    }
    const ex = analysisExtracted;

    // Q1: Business name — prefer interview answer
    const businessNameFinal = data.businessName || business_name;
    // Q2: Core description — used as schema description and opening prose
    const coreDescription = data.coreDescription || ex.tagline || '';
    // Q3: Products & Programs — use actual user-provided names only
    const productsLine = data.productsServices || '';
    // Q4: Founder/Expert — full sentence from user
    const founderLine = data.founderExpert || '';
    // Q5: Proprietary frameworks
    const frameworksLine = data.proprietaryFrameworks || '';
    // Q6: Credibility signals
    const credibilitySignals = data.credibilitySignals || '';
    // Q7: Priority message
    const priorityMessage = data.priorityMessage || '';
    // Q8: Common question
    const commonQuestion = data.commonQuestion || '';
    // Q9: Misconceptions
    const misconceptions = data.misconceptions || '';
    // Q10–Q13: Search & Citations
    const proofPoints = data.proofPoints || '';
    const topicOwnership = data.topicOwnership || '';
    const competitorDiff = data.competitorDiff || '';
    const knowledgePanel = data.knowledgePanel || '';
    // Scraped-only fields (not overridden by interview)
    const audienceLine = ex.targetAudience || '';

    const files = {};
    const zip = new JSZip();

    // Helper to add file to both storage objects
    const addFile = (filename, content) => {
      files[filename] = content;
      zip.file(filename, content);
    };

    // ===== BASIC PACKAGE FILES (7 files) =====

    // 1. llm.txt
    const llmTxtParts = [];
    llmTxtParts.push(`# ${businessNameFinal}`);
    llmTxtParts.push(`<!-- Generated by AEO File Generator v2.0 | ${new Date().toISOString().split('T')[0]} -->`);

    if (priorityMessage) {
      llmTxtParts.push(`\n## Priority Context`);
      llmTxtParts.push(priorityMessage);
    }

    llmTxtParts.push(`\n## Overview`);
    let overviewPara = coreDescription || `${businessNameFinal} operates at ${website_url}.`;
    if (data.yearEstablished) overviewPara += ` Established in ${data.yearEstablished}.`;
    if (founderLine) overviewPara += ` Led by ${founderLine}.`;
    llmTxtParts.push(overviewPara);

    if (productsLine) {
      llmTxtParts.push(`\n## Products and Services`);
      let servicesPara = productsLine;
      if (frameworksLine) servicesPara += `\n\nProprietary methodologies and frameworks: ${frameworksLine}.`;
      llmTxtParts.push(servicesPara);
    }

    if (credibilitySignals) {
      llmTxtParts.push(`\n## Authority & Credibility`);
      llmTxtParts.push(credibilitySignals);
    }

    if (proofPoints) {
      llmTxtParts.push(`\n## Proof Points`);
      llmTxtParts.push(proofPoints);
    }

    if (competitorDiff) {
      llmTxtParts.push(`\n## What Makes Us Different`);
      llmTxtParts.push(competitorDiff);
    }

    if (audienceLine) {
      llmTxtParts.push(`\n## Who This Is For`);
      llmTxtParts.push(`${businessNameFinal} serves ${audienceLine}.`);
    }

    if (commonQuestion) {
      llmTxtParts.push(`\n## Frequently Asked`);
      llmTxtParts.push(`Q: ${commonQuestion}`);
    }

    if (misconceptions) {
      llmTxtParts.push(`\n## Common Misconceptions`);
      llmTxtParts.push(misconceptions);
    }

    llmTxtParts.push(`\n## Contact`);
    const contactLines = [`Email: ${data.contactEmail || 'Not provided'}`];
    if (data.address) contactLines.push(`Address: ${data.address}`);
    if (data.socialLinks) contactLines.push(`Social Media:\n${data.socialLinks}`);
    llmTxtParts.push(contactLines.join('\n'));

    llmTxtParts.push(`\n## AI Crawler Permissions`);
    llmTxtParts.push(data.aiCrawlers ? Object.keys(data.aiCrawlers).filter(k => data.aiCrawlers[k]).map(k => k.charAt(0).toUpperCase() + k.slice(1)).join(', ') : 'All crawlers allowed');

    const llmTxt = llmTxtParts.join('\n');
    addFile('llm.txt', llmTxt);

    // 2. robots.txt
    const allowedCrawlers = data.aiCrawlers || {};
    const robotsTxt = `User-agent: *\nAllow: /\n\n${allowedCrawlers.chatgpt !== false ? '# ChatGPT\nUser-agent: GPTBot\nAllow: /\n' : '# ChatGPT\nUser-agent: GPTBot\nDisallow: /\n'}${allowedCrawlers.google !== false ? '# Google Bard\nUser-agent: Google-Extended\nAllow: /\n' : '# Google Bard\nUser-agent: Google-Extended\nDisallow: /\n'}${allowedCrawlers.anthropic !== false ? '# Claude\nUser-agent: anthropic-ai\nAllow: /\n' : '# Claude\nUser-agent: anthropic-ai\nDisallow: /\n'}${allowedCrawlers.perplexity !== false ? '# Perplexity\nUser-agent: PerplexityBot\nAllow: /\n' : '# Perplexity\nUser-agent: PerplexityBot\nDisallow: /\n'}\n# Meta\nUser-agent: Meta-ExternalAgent\nAllow: /\n\n# Amazon\nUser-agent: Amazonbot\nAllow: /\n\n# Apple\nUser-agent: Applebot\nAllow: /\n\n# Cohere\nUser-agent: cohere-ai\nAllow: /\n\n# AI2\nUser-agent: AI2Bot\nAllow: /\n\nSitemap: ${website_url}/sitemap.xml\nSitemap: ${website_url}/ai-sitemap.xml`;
    addFile('robots.txt', robotsTxt);

    // 3. sitemap.xml — built from scraped internal link inventory when available,
    //    with fallback to siteStructure-derived top-level URLs. ai-sitemap.xml is
    //    emitted as a copy for backward compatibility with any existing robots.txt
    //    entries pointing to the legacy filename.
    const today = new Date().toISOString().split('T')[0];
    const siteStructure = ex.siteStructure || {};

    const changefreqFor = (path) => {
      const p = path.toLowerCase();
      if (p === '/' || p === '') return 'weekly';
      if (/\/(blog|news|articles?)(\/|$)/.test(p)) return 'weekly';
      if (/\/(product|shop|store|pricing)(\/|$)/.test(p)) return 'daily';
      if (/\/(about|contact|team|privacy|terms)(\/|$)/.test(p)) return 'monthly';
      return 'weekly';
    };
    const priorityFor = (path) => {
      if (path === '/' || path === '' || path === website_url) return '1.0';
      const depth = (path.match(/\//g) || []).length;
      if (depth <= 1) return '0.8';
      if (depth === 2) return '0.7';
      return '0.6';
    };
    const toAbsolute = (href) => {
      try {
        return new URL(href, website_url).toString().replace(/\/$/, '') || website_url;
      } catch {
        return null;
      }
    };

    const sitemapUrlSet = new Set([website_url.replace(/\/$/, '')]);
    if (Array.isArray(ex.internalLinks)) {
      for (const link of ex.internalLinks) {
        const absolute = toAbsolute(link?.url || link);
        if (absolute && sitemapUrlSet.size < 50) sitemapUrlSet.add(absolute);
      }
    }
    if (sitemapUrlSet.size <= 1) {
      // Fallback: seed from siteStructure flags
      if (siteStructure.hasProducts) sitemapUrlSet.add(`${website_url.replace(/\/$/, '')}/products`);
      if (siteStructure.hasServices) sitemapUrlSet.add(`${website_url.replace(/\/$/, '')}/services`);
      if (siteStructure.hasBlog) sitemapUrlSet.add(`${website_url.replace(/\/$/, '')}/blog`);
      if (siteStructure.hasAbout) sitemapUrlSet.add(`${website_url.replace(/\/$/, '')}/about`);
      if (siteStructure.hasContact) sitemapUrlSet.add(`${website_url.replace(/\/$/, '')}/contact`);
    }

    const sitemapEntries = Array.from(sitemapUrlSet).map((loc) => {
      let pathOnly = '/';
      try { pathOnly = new URL(loc).pathname || '/'; } catch {}
      return `  <url>\n    <loc>${loc}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>${changefreqFor(pathOnly)}</changefreq>\n    <priority>${priorityFor(pathOnly)}</priority>\n  </url>`;
    }).join('\n');
    const sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${sitemapEntries}\n</urlset>`;
    addFile('sitemap.xml', sitemapXml);
    addFile('ai-sitemap.xml', sitemapXml);

    // 4. schema-organization.json
    const schemaOrg = {
      "@context": "https://schema.org",
      "@type": "Organization",
      "name": businessNameFinal,
      "url": website_url,
      "description": coreDescription || productsLine || "",
      "email": data.contactEmail || ""
    };

    if (data.hasPhysicalLocation === 'yes' && data.address) {
      schemaOrg["address"] = { "@type": "PostalAddress", "streetAddress": data.address };
    }

    if (data.yearEstablished) {
      schemaOrg["foundingDate"] = String(data.yearEstablished);
    }

    // Q4: Founder — extract just the name (first segment before comma) from the interview sentence
    if (founderLine) {
      const founderNameOnly = founderLine.split(',')[0].trim();
      schemaOrg["founder"] = { "@type": "Person", "name": founderNameOnly, "description": founderLine };
    } else if (ex.founderName) {
      schemaOrg["founder"] = {
        "@type": "Person",
        "name": ex.founderName,
        ...(ex.founderRole ? { "jobTitle": ex.founderRole } : {})
      };
    }

    // Page title as headline (separate from business name and description)
    if (ex.pageTitle) {
      schemaOrg["headline"] = ex.pageTitle;
    }

    // Logo: look for og:image or apple-touch-icon from extracted data
    if (ex.logoUrl) {
      schemaOrg["logo"] = { "@type": "ImageObject", "url": ex.logoUrl };
    }

    if (data.hasPhysicalLocation === 'no' || !data.address) {
      schemaOrg["areaServed"] = "Worldwide";
    } else if (data.address) {
      schemaOrg["areaServed"] = data.address;
    }

    // knowsAbout: prefer Q11 topicOwnership, then industry keywords, then content focus
    const knowsAbout = [];
    if (topicOwnership) {
      topicOwnership.split(/[,\n]/).map(s => s.trim()).filter(Boolean).forEach(t => {
        if (!knowsAbout.includes(t)) knowsAbout.push(t);
      });
    }
    if (ex.industryKeywords?.length > 0) {
      ex.industryKeywords.slice(0, 5).forEach(k => { if (!knowsAbout.includes(k)) knowsAbout.push(k); });
    }
    if (data.contentFocus) {
      const focusMap = { products: 'Products', expertise: 'Industry Expertise', story: 'Company Story', team: 'Team' };
      Object.keys(data.contentFocus).filter(k => data.contentFocus[k]).forEach(k => {
        if (focusMap[k] && !knowsAbout.includes(focusMap[k])) knowsAbout.push(focusMap[k]);
      });
    }
    if (data.industry && !knowsAbout.includes(data.industry)) knowsAbout.push(data.industry);
    if (knowsAbout.length > 0) schemaOrg["knowsAbout"] = knowsAbout;

    // award: pull award-like mentions from credibilitySignals (Q6)
    if (credibilitySignals) {
      const awardMatches = credibilitySignals.match(/(?:awarded?|winner of|featured in|honored with|named [a-z]+)[^.,;\n]{3,80}/gi);
      if (awardMatches && awardMatches.length > 0) {
        schemaOrg["award"] = awardMatches.map(a => a.trim()).slice(0, 5);
      }
    }

    // numberOfEmployees: detect counts in proofPoints (Q10)
    if (proofPoints) {
      const employeeMatch = proofPoints.match(/(\d[\d,]*)\s*(?:employees|team members|staff|contractors)/i);
      if (employeeMatch) {
        schemaOrg["numberOfEmployees"] = employeeMatch[1].replace(/,/g, '');
      }
    }

    if (data.socialLinks) {
      schemaOrg["sameAs"] = data.socialLinks.split('\n').filter(l => l.trim());
    }

    // hasOfferCatalog: parse Q3 productsServices into Offer items
    if (productsLine) {
      const offerItems = productsLine
        .split(/[,\n]/)
        .map(s => s.trim())
        .filter(s => s.length > 2 && s.length < 120)
        .slice(0, 10)
        .map(name => ({
          "@type": "Offer",
          "itemOffered": { "@type": "Service", "name": name }
        }));
      if (offerItems.length > 0) {
        schemaOrg["hasOfferCatalog"] = {
          "@type": "OfferCatalog",
          "name": `${businessNameFinal} — Products & Services`,
          "itemListElement": offerItems
        };
      }
    }

    addFile('schema-organization.json', JSON.stringify(schemaOrg, null, 2));

    // 5. schema-website.json
    const schemaWebsite = {
      "@context": "https://schema.org",
      "@type": "WebSite",
      "name": businessNameFinal,
      "url": website_url,
      "description": coreDescription || productsLine || "",
      ...(ex.pageTitle ? { "headline": ex.pageTitle } : {}),
      "publisher": {
        "@type": "Organization",
        "name": businessNameFinal
      }
    };
    addFile('schema-website.json', JSON.stringify(schemaWebsite, null, 2));

    // 6. schema-faqpage.json — FAQPage schema from scraped faqItems + Q8 commonQuestion.
    //    Google uses FAQPage schema for rich results and AI Overview citations.
    const faqItemsScraped = Array.isArray(ex.faqItems) ? ex.faqItems : [];
    const faqMainEntity = [];
    for (const item of faqItemsScraped) {
      if (faqMainEntity.length >= 10) break;
      if (item?.q && item?.a) {
        faqMainEntity.push({
          "@type": "Question",
          "name": String(item.q).trim(),
          "acceptedAnswer": { "@type": "Answer", "text": String(item.a).trim() }
        });
      }
    }
    if (commonQuestion && faqMainEntity.length < 10) {
      faqMainEntity.push({
        "@type": "Question",
        "name": commonQuestion,
        "acceptedAnswer": {
          "@type": "Answer",
          "text": `See ${website_url} for the full answer from ${businessNameFinal}.`
        }
      });
    }
    if (faqMainEntity.length > 0) {
      const schemaFaq = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": faqMainEntity
      };
      addFile('schema-faqpage.json', JSON.stringify(schemaFaq, null, 2));
    }

    // 7. schema-person.json — E-E-A-T signal. Primary GEO file.
    //    Phase 1 uses Q4 founderExpert + scraped founderName/Role + socialLinks.
    //    Q11 (knowsAbout) and Q13 (description) layer in during Phase 2.
    const founderNameFromQ4 = founderLine ? founderLine.split(',')[0].trim() : '';
    const personName = founderNameFromQ4 || ex.founderName || '';
    if (personName) {
      const schemaPerson = {
        "@context": "https://schema.org",
        "@type": "Person",
        "name": personName
      };
      if (ex.founderRole) schemaPerson["jobTitle"] = ex.founderRole;
      schemaPerson["description"] = data.knowledgePanel || founderLine || `${personName} of ${businessNameFinal}.`;
      schemaPerson["worksFor"] = {
        "@type": "Organization",
        "name": businessNameFinal,
        "url": website_url
      };
      const knowsAboutPerson = [];
      if (data.topicOwnership) {
        data.topicOwnership.split(/[,\n]/).map(s => s.trim()).filter(Boolean).forEach(t => {
          if (!knowsAboutPerson.includes(t)) knowsAboutPerson.push(t);
        });
      }
      if (Array.isArray(ex.industryKeywords)) {
        ex.industryKeywords.slice(0, 5).forEach(k => {
          if (!knowsAboutPerson.includes(k)) knowsAboutPerson.push(k);
        });
      }
      if (knowsAboutPerson.length > 0) schemaPerson["knowsAbout"] = knowsAboutPerson;

      const sameAsPerson = [];
      if (Array.isArray(ex.socialLinks)) {
        ex.socialLinks.forEach(l => { if (l && !sameAsPerson.includes(l)) sameAsPerson.push(l); });
      }
      if (data.socialLinks) {
        data.socialLinks.split('\n').map(s => s.trim()).filter(Boolean).forEach(l => {
          if (!sameAsPerson.includes(l)) sameAsPerson.push(l);
        });
      }
      if (sameAsPerson.length > 0) schemaPerson["sameAs"] = sameAsPerson;

      if (ex.siteStructure?.hasAbout) {
        schemaPerson["url"] = `${website_url.replace(/\/$/, '')}/about`;
      }

      addFile('schema-person.json', JSON.stringify(schemaPerson, null, 2));
    }

    // 8. meta-tags.html — copy-paste Open Graph + Twitter Card block.
    const metaDescForTags = (coreDescription || productsLine || '').replace(/"/g, '&quot;').split('\n')[0].slice(0, 200);
    const metaTitle = businessNameFinal.replace(/"/g, '&quot;');
    const metaImage = ex.logoUrl || '';
    const metaTagsHtml = `<!-- ============================================\n     OPEN GRAPH & TWITTER CARD META TAGS\n     Copy and paste this block into your <head> tag\n     Generated by AEO File Generator v2.0 — ${today}\n     ============================================ -->\n<meta property="og:title" content="${metaTitle}" />\n<meta property="og:description" content="${metaDescForTags}" />\n<meta property="og:type" content="website" />\n<meta property="og:url" content="${website_url}" />\n${metaImage ? `<meta property="og:image" content="${metaImage}" />\n` : `<!-- <meta property="og:image" content="https://your-site.com/path/to/image.png" /> -->\n`}<meta name="twitter:card" content="summary_large_image" />\n<meta name="twitter:title" content="${metaTitle}" />\n<meta name="twitter:description" content="${metaDescForTags}" />\n${metaImage ? `<meta name="twitter:image" content="${metaImage}" />\n` : `<!-- <meta name="twitter:image" content="https://your-site.com/path/to/image.png" /> -->\n`}`;
    addFile('meta-tags.html', metaTagsHtml);

    // 8b. seo-audit.md — technical SEO audit using scraper findings.
    const pass = '✅';
    const fail = '❌';
    const warn = '⚠️';
    const auditRobots = ex.existingRobotsTxt?.present ? pass : fail;
    const auditSitemap = ex.existingSitemap?.present ? `${pass} (${ex.existingSitemap.urlCount} URLs)` : fail;
    const auditCanonical = ex.canonical?.present ? `${pass} (${ex.canonical.url || 'present'})` : fail;
    const auditMetaDesc = ex.metaDescription ? pass : fail;
    const auditOgTitle = ex.ogTags?.title ? pass : fail;
    const auditOgDesc = ex.ogTags?.description ? pass : fail;
    const auditOgImage = ex.ogTags?.image ? pass : fail;
    const auditOgType = ex.ogTags?.type ? pass : fail;
    const auditTwitterCard = ex.ogTags?.twitterCard ? pass : fail;
    const auditHttps = website_url.startsWith('https://') ? pass : fail;

    const h1Count = (ex.headingStructure || []).filter(h => h.level === 1).length;
    const auditH1 = h1Count === 1 ? pass : (h1Count === 0 ? fail : warn);

    const existingSchemaTypes = ex.existingSchema?.types || [];
    const hasExistingSchema = existingSchemaTypes.length > 0;

    const providedSchemas = ['Organization', 'WebSite'];
    if (faqMainEntity.length > 0) providedSchemas.push('FAQPage');
    if (personName) providedSchemas.push('Person');
    if (package_tier === 'complete') {
      providedSchemas.push('WebPage', 'BreadcrumbList');
      if (data.hasPhysicalLocation === 'yes') providedSchemas.push('LocalBusiness');
    }

    const schemaGaps = providedSchemas.filter(s => !existingSchemaTypes.includes(s));

    const quickWins = [];
    if (!ex.ogTags?.title || !ex.ogTags?.description || !ex.ogTags?.image) {
      quickWins.push('Paste the provided meta-tags.html block into your site <head> — this adds the missing Open Graph tags.');
    }
    if (!ex.canonical?.present) {
      quickWins.push('Add a canonical URL tag to every page: <link rel="canonical" href="YOUR_CANONICAL_URL" />.');
    }
    if (!ex.existingSitemap?.present) {
      quickWins.push('Upload the provided sitemap.xml to your site root and submit it to Google Search Console.');
    }
    if (!ex.existingRobotsTxt?.present) {
      quickWins.push('Upload the provided robots.txt to your site root.');
    }
    if (!ex.metaDescription) {
      quickWins.push('Add a <meta name="description"> tag of 150–160 characters to every page.');
    }
    if (h1Count === 0) {
      quickWins.push('Add exactly one <h1> tag per page describing the page\'s primary topic.');
    } else if (h1Count > 1) {
      quickWins.push(`You have ${h1Count} <h1> tags on the homepage. Use only one <h1> per page; downgrade the others to <h2>.`);
    }
    if (schemaGaps.length > 0) {
      quickWins.push(`Install these schema types (not currently detected on your site): ${schemaGaps.join(', ')}.`);
    }

    const platform = ex.platform || 'Custom/Other';
    const platformInstructions = {
      'WordPress': 'Use a plugin like RankMath or Yoast SEO to install the provided schema JSON-LD. Upload the static files (robots.txt, sitemap.xml, llm.txt) via your host\'s file manager or an FTP client to /public_html/.',
      'Shopify': 'Paste the schema JSON inside a <script type="application/ld+json"> block in theme.liquid within <head>. Static files like robots.txt are managed in Online Store → Preferences → robots.txt customization.',
      'Wix': 'In Wix, go to Settings → Custom Code and paste the meta-tags.html + each schema JSON as a Custom Code snippet targeting <head> on all pages.',
      'Squarespace': 'Paste the schema JSON in Settings → Advanced → Code Injection → Header. Meta tags go in the same place.',
      'Webflow': 'Paste schema JSON in Project Settings → Custom Code → Head. For page-specific schema, use Page Settings → Custom Code → Head.',
      'Framer': 'In Site Settings → General → Custom Code → End of <head>, paste the meta tags and schema JSON blocks.',
      'Kajabi': 'In Site Settings → Advanced Settings → Site header code, paste the schema JSON and meta tags.',
      'Ghost': 'In Admin → Settings → Code Injection → Site Header, paste the schema JSON and meta tags.',
      'Custom/Other': 'Paste the schema JSON inside a <script type="application/ld+json"> block in your site <head>. Upload robots.txt, sitemap.xml, and the other static files to your site root directory.'
    };

    const seoAuditMd = [
      `# SEO Audit — ${businessNameFinal}`,
      ``,
      `Source: ${website_url}  `,
      `Generated: ${today}  `,
      `Detected platform: **${platform}**`,
      ``,
      `---`,
      ``,
      `## 1. Technical SEO Status`,
      ``,
      `| Check | Status |`,
      `|-------|--------|`,
      `| HTTPS | ${auditHttps} |`,
      `| robots.txt present | ${auditRobots} |`,
      `| sitemap.xml present | ${auditSitemap} |`,
      `| Canonical URL | ${auditCanonical} |`,
      `| Meta description | ${auditMetaDesc} |`,
      `| Exactly one H1 | ${auditH1} (${h1Count} found) |`,
      `| og:title | ${auditOgTitle} |`,
      `| og:description | ${auditOgDesc} |`,
      `| og:image | ${auditOgImage} |`,
      `| og:type | ${auditOgType} |`,
      `| twitter:card | ${auditTwitterCard} |`,
      ``,
      `## 2. Schema Markup Status`,
      ``,
      hasExistingSchema
        ? `Your site already has the following schema types:\n\n${existingSchemaTypes.map(t => `- ${t}`).join('\n')}`
        : `No JSON-LD or microdata schema was detected on your homepage.`,
      ``,
      `This package provides schema JSON for: ${providedSchemas.join(', ')}.`,
      ``,
      schemaGaps.length > 0
        ? `**Schemas to install (not currently on your site):** ${schemaGaps.join(', ')}.`
        : `All provided schema types are already present on your site — use the generated files to refresh or extend the existing markup.`,
      ``,
      `## 3. Missing Quick Wins`,
      ``,
      quickWins.length > 0 ? quickWins.map((w, i) => `${i + 1}. ${w}`).join('\n') : 'No quick wins found — your technical SEO baseline looks strong. Focus on content and GEO signals.',
      ``,
      `## 4. Platform-Specific Instructions (${platform})`,
      ``,
      platformInstructions[platform] || platformInstructions['Custom/Other'],
      ``,
      `## 5. Next Steps`,
      ``,
      `1. Address the quick wins above first — they unlock the largest gains for the least effort.`,
      `2. Validate every schema file at https://validator.schema.org and https://search.google.com/test/rich-results.`,
      `3. Submit your sitemap.xml to Google Search Console and Bing Webmaster Tools.`,
      `4. Re-run this generator every 90 days or when your business offering changes significantly.`
    ].join('\n');
    addFile('seo-audit.md', seoAuditMd);

    // 9. README.md
    const readme = `# AEO Package - ${business_name}\n\n## Package Type: ${package_tier.toUpperCase()}\n\nThis package contains SEO + AEO + GEO optimized files for your website: ${website_url}\n\n## Files Included\n\n${package_tier === 'basic' ? `### Basic Package:\n- llm.txt - AI-readable business information\n- robots.txt - AI crawler permissions + sitemap directive\n- sitemap.xml - Standard sitemap (submit to search engines)\n- ai-sitemap.xml - Legacy filename kept for backward compatibility\n- schema-organization.json - Organization structured data (SEO + AEO)\n- schema-website.json - Website structured data (SEO)\n- schema-faqpage.json - FAQ schema for rich results + AI Overview citations (when FAQ content is available)\n- schema-person.json - Person/E-E-A-T schema (when founder data is available)\n- meta-tags.html - Open Graph + Twitter Card copy-paste block\n- seo-audit.md - Technical SEO audit with platform-specific fixes\n- README.md - This file\n- Implementation_Guide.md - Step-by-step implementation instructions` : `### Complete Package (includes all Basic files plus):\n- llms.txt - Extended AI context\n- llms-full.txt - Comprehensive AI dataset\n- humans.txt - Human-readable site info\n- security.txt - Security contact information\n- .well-known/ai.json - AI configuration (business name, services, allowed crawlers)\n- schema-webpage.json - WebPage structured data\n- schema-breadcrumb.json - Breadcrumb navigation schema\n${data.hasPhysicalLocation === 'yes' ? '- schema-localbusiness.json - LocalBusiness structured data\n' : ''}- Verification_Checklist.md - Post-implementation checklist`}\n\n## Quick Start\n\n1. Read the Implementation_Guide.md file\n2. Upload files to your website root directory\n3. Paste meta-tags.html into your site's <head> section\n4. Submit sitemap.xml to Google Search Console\n5. Verify schema with Google Rich Results Test\n\n## Support\n\nFor questions or issues, contact: ${data.contactEmail || 'support'}\n\nGenerated: ${new Date().toISOString().split('T')[0]}\nExpires: 90 days from generation\n`;
    addFile('README.md', readme);

    // 7. Implementation_Guide.md — rewritten for v2.0 (SEO + AEO + GEO).
    const platformName = data.platform || ex.platform || 'Custom/Other';
    const platformSeoSteps = {
      'WordPress': [
        `1. Install RankMath (free) or Yoast SEO Premium. Both support custom JSON-LD.`,
        `2. Paste each schema-*.json file into RankMath → Titles & Meta → Global Meta → Advanced → Custom JSON-LD (or the Yoast equivalent).`,
        `3. Upload robots.txt, sitemap.xml, ai-sitemap.xml, llm.txt, humans.txt, security.txt, and meta-tags.html content to /public_html/ via your host's file manager or SFTP.`,
        `4. In your theme's functions.php (or a snippets plugin), add the meta-tags.html content inside wp_head via an add_action hook if your SEO plugin doesn't already cover Open Graph.`
      ],
      'Shopify': [
        `1. In Shopify admin: Online Store → Preferences → Edit robots.txt.liquid. Merge the provided robots.txt directives.`,
        `2. Online Store → Navigation → Pages. Create a page for llm.txt, llms.txt, and llms-full.txt if Shopify won't serve them at the root (Shopify restricts root-level static files). Alternatively, use a subdomain or reverse proxy.`,
        `3. Paste schema JSON-LD blocks into theme.liquid within <head>, wrapped in <script type="application/ld+json"> tags. Do this before </head>.`,
        `4. meta-tags.html content goes into theme.liquid <head> as well.`
      ],
      'Wix': [
        `1. Settings → Custom Code. Add each schema-*.json as a Custom Code snippet targeting <head> on all pages, wrapped in <script type="application/ld+json">.`,
        `2. meta-tags.html content: paste as another Custom Code snippet targeting <head>.`,
        `3. Upload robots.txt directives via Marketing & SEO → SEO Settings → Advanced SEO → robots.txt.`,
        `4. Submit sitemap.xml via Google Search Console — Wix generates its own sitemap at /sitemap.xml, so you'll use the Wix-managed file unless you're on Premium with DNS control.`
      ],
      'Squarespace': [
        `1. Settings → Advanced → Code Injection → Header. Paste each schema-*.json wrapped in <script type="application/ld+json"> tags, followed by the meta-tags.html content.`,
        `2. Squarespace automatically serves robots.txt at /robots.txt — you can't replace it, but you can review it at /robots.txt.`,
        `3. sitemap.xml is auto-generated by Squarespace. Use the provided sitemap.xml as a reference if customizing via Developer Mode.`,
        `4. llm.txt, llms.txt, and similar files require Developer Mode or a subdomain.`
      ],
      'Webflow': [
        `1. Project Settings → Custom Code → Head Code. Paste each schema-*.json inside <script type="application/ld+json"> tags.`,
        `2. Paste meta-tags.html content into Head Code as well.`,
        `3. Project Settings → SEO → Indexing → robots.txt: paste the provided content.`,
        `4. Webflow auto-generates a sitemap.xml. Use the provided sitemap.xml as a reference for structure.`
      ],
      'Framer': [
        `1. Site Settings → General → Custom Code → End of <head>. Paste meta-tags.html and each schema-*.json (wrapped in <script type="application/ld+json">).`,
        `2. Site Settings → SEO → Custom Domain: upload robots.txt at the domain level if supported, or rely on Framer's defaults.`,
        `3. Framer generates sitemap.xml automatically.`
      ],
      'Kajabi': [
        `1. Site Settings → Advanced Settings → Site header code. Paste schema JSON-LD blocks and meta-tags.html content.`,
        `2. Kajabi manages robots.txt at the account level; request custom edits from support if needed.`,
        `3. llm.txt and similar static files need a subdomain or external host.`
      ],
      'Ghost': [
        `1. Admin → Settings → Code Injection → Site Header. Paste schema JSON-LD and meta-tags.html.`,
        `2. Admin → Settings → Labs or via theme: edit robots.txt.`,
        `3. Ghost auto-generates sitemap.xml.`
      ],
      'Custom/Other': [
        `1. Upload robots.txt, sitemap.xml, ai-sitemap.xml, llm.txt, humans.txt, security.txt, and meta-tags.html (as HTML) to your site root directory.`,
        `2. In your HTML <head>, paste each schema-*.json wrapped in <script type="application/ld+json"> tags.`,
        `3. Also in <head>, paste the meta-tags.html content.`,
        `4. If you use a CDN, purge cache after upload.`
      ]
    };
    const seoStepLines = (platformSeoSteps[platformName] || platformSeoSteps['Custom/Other']).join('\n');

    const implGuideParts = [
      `# Implementation Guide — ${businessNameFinal}`,
      ``,
      `Detected platform: **${platformName}**  `,
      `Package tier: **${package_tier.toUpperCase()}**  `,
      `Generated: ${today}`,
      ``,
      `This guide covers three disciplines: **SEO** (traditional search), **AEO** (AI answer engines), and **GEO** (AI-generated search results). Complete the quick start first; tackle the rest in order.`,
      ``,
      `---`,
      ``,
      `## Quick Start (5 minutes)`,
      ``,
      `1. Upload \`robots.txt\`, \`sitemap.xml\`, and \`llm.txt\` to your site root so they resolve at ${website_url}/robots.txt etc.`,
      `2. Paste the contents of \`meta-tags.html\` into every page's <head> (or global head, depending on platform).`,
      `3. Paste each \`schema-*.json\` into a <script type="application/ld+json"> block in <head>.`,
      `4. Submit \`sitemap.xml\` in Google Search Console.`,
      `5. Read \`seo-audit.md\` for your personalized quick-win list.`,
      ``,
      `---`,
      ``,
      `## 1. SEO Implementation`,
      ``,
      `### Platform-specific steps for ${platformName}`,
      ``,
      seoStepLines,
      ``,
      `### Validate`,
      ``,
      `- Run every schema file through https://validator.schema.org and https://search.google.com/test/rich-results.`,
      `- Use Google Search Console's URL Inspection tool to confirm canonical, indexing, and rich results status.`,
      ``,
      `## 2. AEO Implementation`,
      ``,
      `- **llm.txt** goes at the site root: ${website_url}/llm.txt. Some crawlers also check /.well-known/llm.txt — symlink or mirror if your host allows it.`,
      `${package_tier === 'complete' ? `- **llms.txt** and **llms-full.txt** also go at the site root: ${website_url}/llms.txt, ${website_url}/llms-full.txt.\n- **.well-known/ai.json** goes at ${website_url}/.well-known/ai.json.` : ''}`,
      `- Verify each file loads by visiting the URL in a private/incognito window. All must return HTTP 200.`,
      `- In robots.txt, confirm the AI crawler directives match your stated preferences.`,
      ``,
      `## 3. GEO Implementation`,
      ``,
      package_tier === 'complete'
        ? `- Open \`geo-content-brief.md\`. Use the **Brand Positioning Statement** as canonical copy in your About page, hero section, and PR boilerplate.\n- Publish the **Quotable Expert Answers** as a FAQ page on your site. AI systems preferentially cite FAQ-formatted content.\n- Work through \`topical-authority-plan.md\` month by month. Don't skip the internal linking map.\n- Reference \`entity-map.json\` when writing author bios, press kits, or bio pages — it's the canonical list of entities, claims, and relationships AI should associate with your brand.\n- Submit \`geo-qa-snippets.json\` structure to any AI-friendly directories or datasets your niche has.`
        : `- Complete tier unlocks the GEO content brief, entity map, Q&A snippets, topical authority plan, and article schema template. Upgrade if you want structured GEO deliverables.`,
      ``,
      `## 4. Verification`,
      ``,
      `- Every schema JSON → Google Rich Results Test + schema.org validator.`,
      `- \`sitemap.xml\` → Google Search Console submission.`,
      `- \`seo-audit.md\` → work through the Quick Wins list in order.`,
      `- Confirm OpenGraph tags render correctly using https://www.opengraph.xyz.`,
      ``,
      `## 5. Maintenance Schedule`,
      ``,
      `- **Quarterly:** re-run the generator so llm.txt, schema, and the GEO brief reflect your current offering, credibility signals, and proof points.`,
      `- **On launch of any new product, program, or major hire:** re-run immediately.`,
      `- **Annually:** review and reaffirm topic ownership (Q11) — topical authority compounds over time only if the topic set stays stable.`,
      ``,
      `## Support`,
      ``,
      `Questions? Contact: ${data.contactEmail || 'support'}`,
      ``
    ];
    const implGuide = implGuideParts.join('\n');
    addFile('Implementation_Guide.md', implGuide);

    // ===== COMPLETE PACKAGE ADDITIONAL FILES =====
    if (package_tier === 'complete') {
      
      // 8. llms.txt
      const llmsTxtParts = [];
      llmsTxtParts.push(`# ${businessNameFinal} — Extended AI Context`);

      if (priorityMessage) {
        llmsTxtParts.push(`\n## Priority Context`);
        llmsTxtParts.push(priorityMessage);
      }

      llmsTxtParts.push(`\n## About the Organization`);
      let aboutPara = coreDescription || `${businessNameFinal} is accessible at ${website_url}.`;
      if (data.hasPhysicalLocation === 'yes' && data.address) aboutPara += ` Based in ${data.address}.`;
      if (data.yearEstablished) aboutPara += ` In operation since ${data.yearEstablished}.`;
      llmsTxtParts.push(aboutPara);

      if (founderLine) {
        llmsTxtParts.push(`\n## Leadership`);
        llmsTxtParts.push(founderLine);
      }

      if (productsLine) {
        llmsTxtParts.push(`\n## Products, Services, and Programs`);
        let fullServicesPara = productsLine;
        if (frameworksLine) fullServicesPara += `\n\nProprietary methodologies and frameworks: ${frameworksLine}.`;
        llmsTxtParts.push(fullServicesPara);
      }

      if (credibilitySignals) {
        llmsTxtParts.push(`\n## Authority & Credibility`);
        llmsTxtParts.push(credibilitySignals);
      }

      if (proofPoints) {
        llmsTxtParts.push(`\n## Proof Points`);
        llmsTxtParts.push(proofPoints);
      }

      if (competitorDiff) {
        llmsTxtParts.push(`\n## Differentiation`);
        llmsTxtParts.push(competitorDiff);
      }

      if (topicOwnership) {
        llmsTxtParts.push(`\n## Topical Authority`);
        llmsTxtParts.push(`${businessNameFinal} establishes expert authority on the following topics:\n\n${topicOwnership}`);
      }

      if (audienceLine) {
        llmsTxtParts.push(`\n## Target Audience`);
        llmsTxtParts.push(`${businessNameFinal} is specifically designed for ${audienceLine}.`);
      }

      if (commonQuestion) {
        llmsTxtParts.push(`\n## Frequently Asked`);
        llmsTxtParts.push(`Q: ${commonQuestion}`);
      }

      if (misconceptions) {
        llmsTxtParts.push(`\n## Common Misconceptions`);
        llmsTxtParts.push(misconceptions);
      }

      llmsTxtParts.push(`\n## Contact and Presence`);
      const presenceLines = [`Website: ${website_url}`, `Email: ${data.contactEmail || 'Not provided'}`];
      if (data.address) presenceLines.push(`Address: ${data.address}`);
      if (data.socialLinks) presenceLines.push(`Social profiles:\n${data.socialLinks}`);
      llmsTxtParts.push(presenceLines.join('\n'));

      const llmsTxt = llmsTxtParts.join('\n');
      addFile('llms.txt', llmsTxt);

      // 9. llms-full.txt — rich, long-form AI context document
      const faqItems = ex.faqItems || [];
      const blogPosts = ex.blogPosts || [];

      const sep = '\n\n---\n\n';
      const llmsFullSections = [];

      // Header
      llmsFullSections.push(
        `# ${businessNameFinal} — Complete AI Knowledge Base\n\n` +
        `This document gives AI language models, search agents, and knowledge retrieval systems a comprehensive, accurate understanding of ${businessNameFinal}.\n\n` +
        `Source: ${website_url}\nGenerated: ${new Date().toISOString().split('T')[0]}`
      );

      // Q7: Priority Context — placed first, before all other sections
      if (priorityMessage) {
        llmsFullSections.push(`## Priority Context\n\n${priorityMessage}`);
      }

      // Q2: Core Description — opening paragraph
      const openingParagraph = coreDescription
        ? `${coreDescription}\n\nThe business is accessible at ${website_url}${data.hasPhysicalLocation === 'yes' && data.address ? ` and also operates from ${data.address}` : ''}.${data.yearEstablished ? ` In operation since ${data.yearEstablished}.` : ''}`
        : `${businessNameFinal} is accessible at ${website_url}.`;
      llmsFullSections.push(`## About ${businessNameFinal}\n\n${openingParagraph}`);

      // Q3: Products & Programs — use user-provided names only
      if (productsLine) {
        let productsPara = `${businessNameFinal} offers the following products and programs:\n\n${productsLine}`;
        if (frameworksLine) productsPara += `\n\n**Methodologies:** ${frameworksLine}`;
        llmsFullSections.push(`## Products, Services, and Programs\n\n${productsPara}`);
      }

      // Q4: Founder/Expert
      if (founderLine) {
        llmsFullSections.push(`## Founder\n\n${founderLine}`);
      }

      // Q5: Proprietary Frameworks (standalone section if no products to attach to)
      if (frameworksLine && !productsLine) {
        llmsFullSections.push(`## Methodologies\n\n${businessNameFinal} uses the following proprietary frameworks and systems:\n\n${frameworksLine}`);
      }

      // Q6: Credibility Signals
      if (credibilitySignals) {
        llmsFullSections.push(`## Authority & Credibility\n\n${credibilitySignals}`);
      }

      // Q10: Proof Points
      if (proofPoints) {
        llmsFullSections.push(`## Proof Points\n\n${proofPoints}`);
      }

      // Q12: Differentiation
      if (competitorDiff) {
        llmsFullSections.push(`## Differentiation\n\nWhat separates ${businessNameFinal} from others in the space:\n\n${competitorDiff}`);
      }

      // Q11: Topical Authority
      if (topicOwnership) {
        const topicList = topicOwnership.split(/[,\n]/).map(t => t.trim()).filter(Boolean);
        const topicBullets = topicList.map(t => `- ${t}`).join('\n');
        llmsFullSections.push(`## Topical Authority\n\n${businessNameFinal} establishes expert authority on the following topics:\n\n${topicBullets}`);
      }

      // Q13: Brand Positioning for Knowledge Panel
      if (knowledgePanel) {
        llmsFullSections.push(`## Brand Positioning\n\n${knowledgePanel}`);
      }

      // Scraped: Target Audience
      if (audienceLine) {
        llmsFullSections.push(`## Who This Is For\n\n${businessNameFinal} is specifically built for ${audienceLine}.`);
      }

      // Q8: Common Question (FAQ) — merged with any scraped FAQ items
      const faqFromInterview = commonQuestion
        ? `**Q: ${commonQuestion}**\n\nA: See ${website_url} for the full answer from ${businessNameFinal}.`
        : null;
      const scrapedFaqContent = faqItems.length > 0
        ? faqItems.map(item => `**Q: ${item.q}**\n\nA: ${item.a}`).join('\n\n')
        : null;
      if (faqFromInterview || scrapedFaqContent) {
        const faqParts = [faqFromInterview, scrapedFaqContent].filter(Boolean);
        llmsFullSections.push(`## Frequently Asked Questions\n\n${faqParts.join('\n\n')}`);
      }

      // Q9: Misconceptions
      if (misconceptions) {
        llmsFullSections.push(`## Common Misconceptions\n\nThe following misconceptions about ${businessNameFinal} should be corrected:\n\n${misconceptions}`);
      }

      // Scraped: Blog content
      if (blogPosts.length > 0) {
        const blogSection = blogPosts.map(post => {
          let entry = `- **${post.title}**`;
          if (post.excerpt) entry += ` — ${post.excerpt}`;
          return entry;
        }).join('\n');
        llmsFullSections.push(`## Content and Blog\n\n${blogSection}`);
      }

      // Contact and Online Presence (scraped fields)
      const contactBlock = [
        `Website: ${website_url}`,
        `Email: ${data.contactEmail || 'Not provided'}`,
        data.address ? `Address: ${data.address}` : null,
        ex.phoneNumber ? `Phone: ${ex.phoneNumber}` : null,
        data.socialLinks ? `\nSocial Profiles:\n${data.socialLinks}` : null
      ].filter(Boolean).join('\n');
      llmsFullSections.push(`## Contact and Online Presence\n\n${contactBlock}`);

      // AI Indexing Permissions
      const crawlerList = data.aiCrawlers
        ? Object.keys(data.aiCrawlers).filter(k => data.aiCrawlers[k]).map(k => k.charAt(0).toUpperCase() + k.slice(1)).join(', ')
        : 'All major AI crawlers';
      llmsFullSections.push(
        `## AI Indexing Permissions\n\n` +
        `${businessNameFinal} explicitly permits the following AI systems to crawl and index their content: ${crawlerList}. ` +
        `This file is provided to ensure AI systems have accurate, up-to-date information directly from the source.`
      );

      const llmsFullTxt = llmsFullSections.join(sep);
      addFile('llms-full.txt', llmsFullTxt);

      // 10. humans.txt
      const humansTxt = `/* TEAM */\nBusiness: ${business_name}\nContact: ${data.contactEmail || 'Not provided'}\nLocation: ${data.address || 'Online'}\n\n/* SITE */\nPlatform: ${data.platform || 'Custom'}\nLanguage: English\nStandards: HTML5, CSS3, Schema.org\nComponents: AI-optimized content\n\n/* THANKS */\nAEO Package Generator - https://aeofilegenerator.com\n`;
      addFile('humans.txt', humansTxt);

      // 11. security.txt
      const securityTxt = `Contact: mailto:${data.contactEmail || 'security@example.com'}\nExpires: ${new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString()}\nPreferred-Languages: en\nCanonical: ${website_url}/.well-known/security.txt\n`;
      addFile('security.txt', securityTxt);

      // 12. .well-known/ai.json
      const crawlerNameMap = {
        chatgpt: 'GPTBot (OpenAI / ChatGPT)',
        claude: 'anthropic-ai (Claude)',
        perplexity: 'PerplexityBot',
        gemini: 'Google-Extended (Gemini)',
        others: 'All other AI crawlers'
      };
      const allowedCrawlerNames = data.aiCrawlers
        ? Object.keys(data.aiCrawlers).filter(k => data.aiCrawlers[k]).map(k => crawlerNameMap[k] || k)
        : Object.values(crawlerNameMap);

      // Derive primary_services — prefer Q3 interview answer, split on comma/newline
      const primaryServices = productsLine
        ? productsLine.split(/[,\n]/).map(s => s.trim()).filter(s => s.length > 2 && s.length < 80).slice(0, 8)
        : [];

      const aiJson = {
        "schema_version": "1.0",
        "business_name": businessNameFinal,
        "website": website_url,
        "description": coreDescription || productsLine || "",
        "primary_services": primaryServices,
        "contact_email": data.contactEmail || "",
        "ai_crawlers_allowed": allowedCrawlerNames,
        "last_updated": new Date().toISOString()
      };
      const wellKnownFolder = zip.folder('.well-known');
      wellKnownFolder.file('ai.json', JSON.stringify(aiJson, null, 2));
      files['.well-known/ai.json'] = JSON.stringify(aiJson, null, 2);

      // 13. schema-webpage.json
      const schemaWebpage = {
        "@context": "https://schema.org",
        "@type": "WebPage",
        "name": businessNameFinal,
        "url": website_url,
        "description": coreDescription || productsLine || "",
        ...(ex.pageTitle ? { "headline": ex.pageTitle } : {}),
        "publisher": {
          "@type": "Organization",
          "name": businessNameFinal
        }
      };
      addFile('schema-webpage.json', JSON.stringify(schemaWebpage, null, 2));

      // 13b. schema-breadcrumb.json — BreadcrumbList built from scraped siteStructure.
      //      Home > category pages. Each item has position, name, and item URL.
      const breadcrumbItems = [{
        "@type": "ListItem",
        "position": 1,
        "name": "Home",
        "item": website_url
      }];
      const addCrumb = (name, path) => {
        if (breadcrumbItems.length >= 5) return;
        breadcrumbItems.push({
          "@type": "ListItem",
          "position": breadcrumbItems.length + 1,
          "name": name,
          "item": `${website_url.replace(/\/$/, '')}${path}`
        });
      };
      const struct = ex.siteStructure || {};
      if (struct.hasProducts) addCrumb('Products', '/products');
      else if (struct.hasServices) addCrumb('Services', '/services');
      if (struct.hasBlog) addCrumb('Blog', '/blog');
      if (struct.hasAbout) addCrumb('About', '/about');
      if (struct.hasContact) addCrumb('Contact', '/contact');
      const schemaBreadcrumb = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": breadcrumbItems
      };
      addFile('schema-breadcrumb.json', JSON.stringify(schemaBreadcrumb, null, 2));

      // 14. schema-localbusiness.json (conditional)
      if (data.hasPhysicalLocation === 'yes') {
        const schemaLocal = {
          "@context": "https://schema.org",
          "@type": "LocalBusiness",
          "name": businessNameFinal,
          "url": website_url,
          "description": coreDescription || productsLine || "",
          "email": data.contactEmail || "",
          "address": {
            "@type": "PostalAddress",
            "streetAddress": data.address || ""
          },
          "geo": {
            "@type": "GeoCoordinates",
            "_comment": "Replace with your latitude and longitude. Use https://www.latlong.net to look them up.",
            "latitude": "0.0",
            "longitude": "0.0"
          },
          "openingHoursSpecification": [{
            "@type": "OpeningHoursSpecification",
            "_comment": "Replace with your actual opening hours. Remove days you are closed.",
            "dayOfWeek": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
            "opens": "09:00",
            "closes": "17:00"
          }],
          "priceRange": "$$"
        };
        if (ex.phoneNumber) schemaLocal["telephone"] = ex.phoneNumber;
        if (Array.isArray(ex.socialLinks) && ex.socialLinks.length > 0) {
          schemaLocal["sameAs"] = ex.socialLinks;
        } else if (data.socialLinks) {
          schemaLocal["sameAs"] = data.socialLinks.split('\n').filter(l => l.trim());
        }
        addFile('schema-localbusiness.json', JSON.stringify(schemaLocal, null, 2));
      }

      // ===== GEO LAYER (Phase 3) =====

      // Helpers used by multiple GEO files
      const splitList = (s) => String(s || '').split(/[,\n]/).map(x => x.trim()).filter(Boolean);
      const proofList = splitList(proofPoints);
      const credibilityList = splitList(credibilitySignals);
      const socialProofList = Array.isArray(ex.socialProofSignals) ? ex.socialProofSignals : [];
      const topicList = splitList(topicOwnership);
      const blogPostsArr = Array.isArray(ex.blogPosts) ? ex.blogPosts : [];
      const scrapedFaqsArr = Array.isArray(ex.faqItems) ? ex.faqItems : [];

      // geo-content-brief.md — the flagship GEO deliverable
      const brandPositioning = (() => {
        const base = coreDescription ? `${businessNameFinal} is ${coreDescription}` : `${businessNameFinal} operates at ${website_url}`;
        const diff = competitorDiff ? ` Unlike others in the space, ${businessNameFinal} ${competitorDiff.replace(/^\W+/, '').replace(/\.$/, '')}.` : '';
        const panel = knowledgePanel ? `\n\n${knowledgePanel}` : '';
        return `${base}${base.endsWith('.') ? '' : '.'}${diff}${panel}`;
      })();

      const claimBlocks = [];
      const allClaimSources = [
        ...proofList.map(p => ({ claim: p, evidence: 'Reported by the business on the questionnaire (Q10 Proof Points).' })),
        ...credibilityList.map(c => ({ claim: c, evidence: 'Reported by the business on the questionnaire (Q6 Credibility Signals).' })),
        ...socialProofList.map(s => ({ claim: s, evidence: `Detected on ${website_url} by the scraper.` }))
      ];
      allClaimSources.slice(0, 5).forEach(({ claim, evidence }) => {
        claimBlocks.push(`**CLAIM:** ${claim}\n**EVIDENCE:** ${evidence}`);
      });

      const quotableAnswers = [];
      scrapedFaqsArr.slice(0, 3).forEach(f => {
        if (f?.q && f?.a) {
          const shortAnswer = String(f.a).split(/(?<=[.!?])\s+/).slice(0, 3).join(' ');
          quotableAnswers.push(`**Q:** ${f.q}\n\n**A (quotable):** ${shortAnswer}`);
        }
      });
      if (commonQuestion && quotableAnswers.length < 5) {
        const sourcePhrase = priorityMessage || coreDescription || `${businessNameFinal} addresses this on ${website_url}`;
        const shortSource = String(sourcePhrase).split(/(?<=[.!?])\s+/).slice(0, 2).join(' ');
        quotableAnswers.push(`**Q:** ${commonQuestion}\n\n**A (quotable):** ${shortSource}`);
      }
      if (misconceptions && quotableAnswers.length < 5) {
        const short = String(misconceptions).split(/(?<=[.!?])\s+/).slice(0, 2).join(' ');
        quotableAnswers.push(`**Q:** What's a common misconception about ${businessNameFinal}?\n\n**A (quotable):** ${short}`);
      }

      const eeatChecklist = [
        `- Add a visible author bio to every blog post that links to the About page (ties to schema-person.json).`,
        `- Display credentials, certifications, and affiliations prominently on the About or bio page.`,
        `- Publish at least one case study per topic cluster with named clients and quantified results.`,
        `- Earn external citations: guest posts, podcast appearances, trade press mentions, and industry awards.`,
        `- Collect reviews on Google Business Profile, Trustpilot, or an industry-specific review site.`,
        `- Keep content dated: add dateModified to articles so crawlers see freshness signals.`
      ].join('\n');

      const differentiationMatrix = competitorDiff
        ? [
            `| Factor | ${businessNameFinal} | Typical alternative |`,
            `|--------|---------------------|--------------------|`,
            `| Primary differentiator | ${competitorDiff.split(/[.\n]/)[0].trim()} | Generic offering in this category |`,
            ...(topicList.slice(0, 3).map(t => `| ${t} | Dedicated focus | Surface-level coverage |`))
          ].join('\n')
        : `*No differentiation statement captured (Q12 was skipped). Add it to sharpen how AI systems position you when recommending.*`;

      const contentRecommendations = (() => {
        const recs = [];
        const coveredTitles = blogPostsArr.map(p => String(p.title || '').toLowerCase());
        topicList.slice(0, 5).forEach(topic => {
          const isCovered = coveredTitles.some(t => t.includes(topic.toLowerCase()));
          recs.push(`- **${topic}** — ${isCovered ? `Existing blog coverage found; strengthen with a case study + FAQ pair for this topic.` : `No blog coverage detected. Publish a pillar article + 3 supporting FAQs to stake the authority claim.`}`);
        });
        if (recs.length === 0) {
          recs.push(`- *No topic ownership captured (Q11 was skipped). Recommend answering Q11 to get targeted content recommendations.*`);
        }
        return recs.join('\n');
      })();

      const geoContentBrief = [
        `# GEO Content Brief — ${businessNameFinal}`,
        ``,
        `Source: ${website_url}  `,
        `Generated: ${today}`,
        ``,
        `This brief gives you the citation-ready content blocks that AI-generated search results (Google AI Overviews, Bing Copilot, Perplexity) pull from when recommending businesses. Treat the claim blocks and quotable answers below as canonical copy for landing pages, blog intros, and PR placements.`,
        ``,
        `---`,
        ``,
        `## 1. Brand Positioning Statement`,
        ``,
        brandPositioning,
        ``,
        `## 2. Citable Claim Blocks`,
        ``,
        claimBlocks.length > 0 ? claimBlocks.join('\n\n') : `*No claims captured. Answer Q6 (credibility signals) or Q10 (proof points) to generate citation-ready statistics.*`,
        ``,
        `## 3. Quotable Expert Answers`,
        ``,
        quotableAnswers.length > 0 ? quotableAnswers.join('\n\n') : `*No Q&A captured. Answer Q8 (common question) and Q9 (misconceptions) to generate quotable content.*`,
        ``,
        `## 4. E-E-A-T Signal Checklist`,
        ``,
        eeatChecklist,
        ``,
        `## 5. Differentiation Matrix`,
        ``,
        differentiationMatrix,
        ``,
        `## 6. Content Recommendations`,
        ``,
        contentRecommendations,
        ``,
        `---`,
        ``,
        `*This brief pairs with entity-map.json, geo-qa-snippets.json, and topical-authority-plan.md. Re-generate the package quarterly or whenever your offering changes.*`
      ].join('\n');
      addFile('geo-content-brief.md', geoContentBrief);

      // entity-map.json — structured knowledge graph for LLM consumption
      const entityMap = {
        primaryEntity: {
          type: "Organization",
          name: businessNameFinal,
          url: website_url,
          description: coreDescription || knowledgePanel || ""
        },
        people: [],
        products: [],
        topics: topicList.map(name => ({ name, relationship: "authority" })),
        frameworks: splitList(frameworksLine).map(name => ({ name, description: `${name} is a proprietary methodology used by ${businessNameFinal}.` })),
        claims: allClaimSources.slice(0, 10).map(({ claim, evidence }) => ({
          statement: claim,
          evidence,
          source: businessNameFinal
        })),
        relationships: []
      };
      if (personName) {
        entityMap.people.push({
          type: "Person",
          name: personName,
          role: ex.founderRole || "",
          expertise: topicList,
          credentials: credibilityList.slice(0, 10)
        });
        entityMap.relationships.push({
          from: personName,
          to: businessNameFinal,
          type: ex.founderRole ? `${ex.founderRole} of` : "founder of"
        });
      }
      if (Array.isArray(ex.namedProductsWithDesc) && ex.namedProductsWithDesc.length > 0) {
        ex.namedProductsWithDesc.forEach(p => {
          if (p?.name) entityMap.products.push({ name: p.name, description: p.description || "" });
        });
      } else if (productsLine) {
        splitList(productsLine).forEach(p => entityMap.products.push({ name: p, description: "" }));
      }
      entityMap.products.forEach(p => {
        entityMap.relationships.push({ from: businessNameFinal, to: p.name, type: "offers" });
      });
      entityMap.topics.forEach(t => {
        entityMap.relationships.push({ from: businessNameFinal, to: t.name, type: "authority on" });
      });
      addFile('entity-map.json', JSON.stringify(entityMap, null, 2));

      // geo-qa-snippets.json — quotable Q&A pairs designed for AI Overview citation
      const qaSnippets = [];
      scrapedFaqsArr.forEach(f => {
        if (!f?.q || !f?.a || qaSnippets.length >= 15) return;
        const answerText = String(f.a).replace(/\s+/g, ' ').trim();
        const citationText = answerText.split(/(?<=[.!?])\s+/).slice(0, 2).join(' ').slice(0, 240);
        qaSnippets.push({
          question: String(f.q).trim(),
          answer: answerText,
          category: "faq",
          source: businessNameFinal,
          citationText
        });
      });
      if (commonQuestion) {
        const answerText = priorityMessage || coreDescription || `${businessNameFinal} addresses this directly at ${website_url}.`;
        qaSnippets.push({
          question: commonQuestion,
          answer: answerText,
          category: "faq",
          source: businessNameFinal,
          citationText: answerText.split(/(?<=[.!?])\s+/).slice(0, 2).join(' ').slice(0, 240)
        });
      }
      if (misconceptions) {
        const answerText = String(misconceptions).replace(/\s+/g, ' ').trim();
        qaSnippets.push({
          question: `What's a common misconception about ${businessNameFinal}?`,
          answer: answerText,
          category: "misconception",
          source: businessNameFinal,
          citationText: answerText.split(/(?<=[.!?])\s+/).slice(0, 2).join(' ').slice(0, 240)
        });
      }
      if (competitorDiff) {
        const answerText = String(competitorDiff).replace(/\s+/g, ' ').trim();
        qaSnippets.push({
          question: `How is ${businessNameFinal} different from others?`,
          answer: answerText,
          category: "comparison",
          source: businessNameFinal,
          citationText: answerText.split(/(?<=[.!?])\s+/).slice(0, 2).join(' ').slice(0, 240)
        });
      }
      if (frameworksLine) {
        const answerText = `${businessNameFinal} uses proprietary methodologies: ${frameworksLine}.`;
        qaSnippets.push({
          question: `How does ${businessNameFinal} work?`,
          answer: answerText,
          category: "how-it-works",
          source: businessNameFinal,
          citationText: answerText.slice(0, 240)
        });
      }
      addFile('geo-qa-snippets.json', JSON.stringify(qaSnippets, null, 2));

      // topical-authority-plan.md
      const topicClusters = (topicList.length > 0 ? topicList : (Array.isArray(ex.industryKeywords) ? ex.industryKeywords.slice(0, 5) : []))
        .slice(0, 8)
        .map((topic) => {
          const covered = blogPostsArr.some(p => String(p.title || '').toLowerCase().includes(topic.toLowerCase()));
          return [
            `### ${topic}`,
            ``,
            `**Pillar topic:** ${topic}`,
            `**Suggested subtopics:**`,
            `- Fundamentals and core definitions for ${topic}`,
            `- ${businessNameFinal}'s point of view on ${topic}`,
            `- Case studies and proof points in ${topic}`,
            `- Common questions and misconceptions about ${topic}`,
            `- Comparison: ${topic} vs adjacent topics`,
            ``,
            `**Content gap:** ${covered ? 'Existing blog coverage found. Strengthen with pillar depth and internal links.' : 'No blog coverage detected. Publish at least 1 pillar article + 3 supporting FAQs.'}`,
            `**Recommended content types:** pillar blog post, FAQ page, case study, comparison article.`
          ].join('\n');
        })
        .join('\n\n');

      const authoritySignals = [
        `- Guest appearances on podcasts within ${topicList[0] || 'your niche'}.`,
        `- Backlinks from trade publications, industry blogs, and partner sites.`,
        `- Quotes in press or newsletters focused on ${topicList[1] || 'your space'}.`,
        `- Speaker slots at relevant conferences or virtual summits.`,
        `- Citations in research reports, whitepapers, or "best of" roundups.`
      ].join('\n');

      const ninetyDay = [
        `**Month 1 — Pillar content.** Publish one pillar article per top-priority topic cluster (aim for 1,500–2,500 words). Link to existing pages and to schema-faqpage.json content.`,
        `**Month 2 — Supporting content.** Produce 3–5 supporting FAQs or short posts per pillar. Update entity-map.json if new products, topics, or people emerge.`,
        `**Month 3 — Authority building.** Pitch guest posts, podcast appearances, and press mentions targeting the authority signals above. Update geo-qa-snippets.json with any new quotable answers you produce.`
      ].join('\n\n');

      const topicalAuthorityMd = [
        `# Topical Authority Plan — ${businessNameFinal}`,
        ``,
        `Generated: ${today}`,
        ``,
        `This plan is the content roadmap that pairs with your schema, llm.txt, and GEO brief. Execute in order. AI systems reward consistent, deep coverage of a focused topic set — not broad, shallow coverage.`,
        ``,
        `---`,
        ``,
        `## 1. Topic Clusters`,
        ``,
        topicClusters || `*No topics captured. Answer Q11 (topic ownership) to generate a targeted cluster plan.*`,
        ``,
        `## 2. Authority Signals to Build`,
        ``,
        authoritySignals,
        ``,
        `## 3. Internal Linking Map`,
        ``,
        `- Every pillar article links to its supporting FAQs and case studies, and vice versa.`,
        `- Each topic cluster links to the About page (schema-person.json) to reinforce E-E-A-T.`,
        `- Cross-link related topics with descriptive anchor text, not "click here".`,
        ``,
        `## 4. 90-Day Action Plan`,
        ``,
        ninetyDay,
        ``,
        `---`,
        ``,
        `*Refresh this plan every quarter. Re-run the generator after publishing new pillar content so the scraper picks up your progress.*`
      ].join('\n');
      addFile('topical-authority-plan.md', topicalAuthorityMd);

      // schema-article.json — reusable Article template
      const schemaArticleTemplate = {
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": "[REPLACE WITH POST TITLE]",
        "description": "[REPLACE WITH 150-CHARACTER SUMMARY]",
        "image": "[REPLACE WITH ARTICLE HERO IMAGE URL]",
        "datePublished": "[REPLACE WITH ISO DATE e.g. 2026-01-15]",
        "dateModified": "[REPLACE WITH ISO DATE e.g. 2026-01-15]",
        "author": {
          "@type": "Person",
          "name": personName || ex.founderName || "[REPLACE WITH AUTHOR NAME]",
          "url": `${website_url.replace(/\/$/, '')}/about`
        },
        "publisher": {
          "@type": "Organization",
          "name": businessNameFinal,
          "url": website_url,
          ...(ex.logoUrl ? { "logo": { "@type": "ImageObject", "url": ex.logoUrl } } : {})
        },
        "mainEntityOfPage": {
          "@type": "WebPage",
          "@id": "[REPLACE WITH CANONICAL POST URL]"
        }
      };
      addFile('schema-article.json', JSON.stringify(schemaArticleTemplate, null, 2));

      // 15. Verification_Checklist.md — v2.0 covers SEO + AEO + GEO.
      const checklist = [
        `# Implementation Verification Checklist — ${businessNameFinal}`,
        ``,
        `Package: **Complete**  |  Generated: ${today}`,
        ``,
        `Work top to bottom. Everything below should be checked before you consider the rollout done.`,
        ``,
        `## Pre-Implementation`,
        `- [ ] Back up current site files and existing schema/meta tags`,
        `- [ ] Review \`seo-audit.md\` and note which quick wins apply`,
        `- [ ] Read \`geo-content-brief.md\` and identify which claims need copy updates`,
        ``,
        `## File Upload Verification (AEO + SEO)`,
        `- [ ] llm.txt accessible at ${website_url}/llm.txt`,
        `- [ ] llms.txt accessible at ${website_url}/llms.txt`,
        `- [ ] llms-full.txt accessible at ${website_url}/llms-full.txt`,
        `- [ ] robots.txt accessible at ${website_url}/robots.txt`,
        `- [ ] sitemap.xml accessible at ${website_url}/sitemap.xml`,
        `- [ ] ai-sitemap.xml accessible at ${website_url}/ai-sitemap.xml (backward compat)`,
        `- [ ] humans.txt accessible at ${website_url}/humans.txt`,
        `- [ ] security.txt accessible at ${website_url}/security.txt`,
        `- [ ] .well-known/ai.json accessible at ${website_url}/.well-known/ai.json`,
        ``,
        `## Schema Implementation (SEO)`,
        `- [ ] schema-organization.json installed (enhanced with knowsAbout + hasOfferCatalog)`,
        `- [ ] schema-website.json installed`,
        `- [ ] schema-webpage.json installed`,
        `- [ ] schema-faqpage.json installed (if FAQ content is present)`,
        `- [ ] schema-person.json installed (E-E-A-T signal)`,
        `- [ ] schema-breadcrumb.json installed`,
        `- [ ] schema-article.json template applied to at least one blog post`,
        data.hasPhysicalLocation === 'yes' ? `- [ ] schema-localbusiness.json installed (geo coordinates + opening hours updated from placeholders)` : ``,
        `- [ ] meta-tags.html Open Graph + Twitter Card block pasted into <head>`,
        `- [ ] Every schema file passes https://validator.schema.org`,
        `- [ ] FAQ + Person + Organization validated at https://search.google.com/test/rich-results`,
        ``,
        `## AI Crawler Configuration (AEO)`,
        `- [ ] robots.txt allows your chosen AI crawlers`,
        `- [ ] Sitemap directive in robots.txt points at ${website_url}/sitemap.xml`,
        `- [ ] Sitemap submitted to Google Search Console and Bing Webmaster Tools`,
        ``,
        `## GEO Rollout`,
        `- [ ] Brand Positioning Statement from geo-content-brief.md used on About + hero`,
        `- [ ] Citable Claim Blocks placed in PR boilerplate, press kit, and key landing pages`,
        `- [ ] Quotable Expert Answers published as a FAQ page`,
        `- [ ] Topical Authority Plan Month 1 pillar content scheduled or drafted`,
        `- [ ] entity-map.json reviewed for accuracy (names, roles, relationships, claims)`,
        `- [ ] geo-qa-snippets.json reviewed and approved for citation`,
        ``,
        `## Testing`,
        `- [ ] All generated files return HTTP 200 in a private window`,
        `- [ ] Schema validates without errors`,
        `- [ ] Mobile-friendly test passed`,
        `- [ ] Lighthouse SEO score ≥ 90`,
        `- [ ] Open Graph preview verified at https://www.opengraph.xyz`,
        ``,
        `## Post-Implementation`,
        `- [ ] Calendar reminder set for quarterly re-generation`,
        `- [ ] Search Console monitoring configured`,
        `- [ ] Team knows where llm.txt / llms.txt / the GEO brief live`,
        ``,
        `---`,
        ``,
        `Completed: ___/___/___    By: _______________`
      ].filter(Boolean).join('\n');
      addFile('Verification_Checklist.md', checklist);
    }

    // Generate ZIP file as Uint8Array
    const zipUint8Array = await zip.generateAsync({ type: 'uint8array' });

    // Create a File-like object for upload
    const zipFileName = `${business_name.replace(/[^a-z0-9]/gi, '_')}_AEO_Package_${package_tier}.zip`;
    const zipFile = new File([zipUint8Array], zipFileName, { type: 'application/zip' });
    
    const uploadResponse = await base44.asServiceRole.integrations.Core.UploadFile({
        file: zipFile
    });
    const zip_url = uploadResponse.file_url;

    // Update generation record
    await base44.asServiceRole.entities.Generation.update(generation_id, {
      files_data: files,
      zip_url: zip_url,
      status: 'completed',
      expires_at: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString()
    });

    return Response.json({ 
      success: true, 
      zip_url: zip_url, 
      files_data: files,
      file_count: Object.keys(files).length 
    });
  } catch (error) {
    console.error('Generate files error:', error);
    
    if (generation_id) {
      try {
        const base44 = createClientFromRequest(req);
        await base44.asServiceRole.entities.Generation.update(generation_id, {
          status: 'failed'
        });
      } catch (updateError) {
        console.error('Failed to update generation status:', updateError);
      }
    }
    
    return Response.json({ error: error.message }, { status: 500 });
  }
});